### ISSUE TITLE
Make `table` kwarg in `read_table*` use the default table name if unspecified

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#121]
Currently, one can create a dataset without specifying a table name, and a default table name (`"table"`) will be assigned as the name of that table.
However, when one then tries to read that dataset using `read_table`, it becomes necessary to explicitly specify a table name:
```python
>>> from kartothek.io.eager import read_table
>>> read_table(dataset_uuid=dataset_uuid, store=store_factory)

TypeError: Parameter `table` is not optional.
```

I suggest the `table` parameter in `kartothek.io.*.read_table*` functions takes the default table name of kartothek if it is not specified, just as the store/update functions do.

This would fail for datasets created with old kartothek versions (due to the change in default table name in v3.0), but AFAIK most of the `read_table` implementations were not available at that time. In case of failure, in the error message it could be clarified that the default table name was used

**Comment by fjetter** [comment]
> This would fail for datasets created with old kartothek versions

That's fine. In older versions the parameter was non-optional anyhow.

**Comment by pbeart** [comment]
Any other modifications of this sort that it would be useful to do all in one go?

**Comment by fjetter** [comment]
@pbeart what kind of modifications are you thinking of?

**Comment by pbeart** [comment]
Just minor QOL things like default parameters etc that could be lumped together
