### ISSUE TITLE
Test against Pandas and NumPy nightlies

### ISSUE THREAD

**Issue by xhochy** [JDASoftwareGroup/kartothek#19]
See https://github.com/xhochy/fletcher/blob/0e51c14fb36ab2e6a6d3086e0e07ff2e5cb2aead/ci/circle_build_linux.sh#L39-L44 on how to install them. This should give us advance warning when they break.

This should be only done on master, especially together with https://github.com/JDASoftwareGroup/kartothek/issues/18

**Comment by kagharpure** [comment]
@xhochy - I the link above, the lines appear to be pulling nightly wheels from https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/

_What_ exactly is that link? Specifically, who maintains it, is it reliabl(y up and updated all the time), can we also depend on it to get nightly NumPy and Pandas wheels?

**Comment by xhochy** [comment]
This is a Rackspace storage bucket which is maintained by https://numfocus.org/ (the foundation backing Pandas and NumPy), and NumPy and Pandas each upload their nightly wheels there. It's the official place ;)

**Comment by kagharpure** [comment]
Sweet, thank you! :)
