### ISSUE TITLE
Allow store URLs for the `store` parameter

### ISSUE THREAD

**Issue by xhochy** [JDASoftwareGroup/kartothek#233]
Currently we require callables that return simplekv stores to be passed to the `store=` parameter. When working with `kartothek` interactively this is quite an annoyance as you always just so `lambda: storefact.get_store_from_url(url)` in these settings. We could save some characters and make the enduser code more readable by also supporting URLs directly.

**Comment by fjetter** [comment]
1. Yes
2. If we stick with the callable we should also add a utils function which does this
3. I believe the simplekv stores are, by now, properly picklable, and if this is not the case for an implementation it should be easily fixable, shouldn't it? I tend to abandon the whole store factory concept entirely. Thoughts about this?

**Comment by fjetter** [comment]
Do we still feel it is necessary to even use a callable? Shouldn't simplekv stores by already compatible?
