### ISSUE TITLE
Extension array support for parquet serialize

### ISSUE THREAD

**Issue by fjetter** [JDASoftwareGroup/kartothek#234]
### Problem description

We should be able to (de-)serialise ExtensionArrays to and from Parquet.

This can be used to enable projects like 
https://github.com/holoviz/spatialpandas
https://github.com/xhochy/fletcher
and much more

cc @jonmmease

**Comment by fjetter** [comment]
Turns out that the support of `pyarrow` for ExtensionArrays seems already sufficient (pyarrow>=0.16.0). `spatialpandas` is a bit special since it uses subclasses of Series/DataFrame. @jonmmease can you work with plain dataframes/series and take care of the conversion yourself?

**Comment by xhochy** [comment]
We need https://issues.apache.org/jira/browse/ARROW-8159 to generate the schema for ExtensionArray based columns.
