### ISSUE TITLE
Minor document correction

### ISSUE THREAD

**Issue by brl0** [JDASoftwareGroup/kartothek#270]
This is a suggestion for a minor documentation correction to the warning section under here:
https://kartothek.readthedocs.io/en/latest/_rst/kartothek.io.dask.dataframe.html#kartothek.io.dask.dataframe.update_dataset_from_ddf

Doc example incorrectly shows this:
`with dask.config(shuffle='tasks'):`

should be:
`with dask.config.set(shuffle='tasks'):`

**Comment by lr4d** [comment]
Thanks @brl0 . Feel free to just open a PR next time
