### ISSUE TITLE
ParquetSerializer.store suppressing blank columns when writing to parquet

### ISSUE THREAD

**Issue by Waterfox83** [JDASoftwareGroup/kartothek#275]
We are seeing an issue with ParquetSerializer.store() method when writing a dataframe to parquet. When a dataframe has no value for a column across all rows, then the column is skipped completely from the parquet file.

Example: In below code, the resulting parquet file has no column named 'colors'

```
def test_data_write():
    df_expected = pd.DataFrame(
        {
            "numbers": [1, 2, 3],
            "colors": [None, None, None],
            "codes": ["R1", "G1", "B1"]
        }
    )
    file_name = "sampleDataset"
    store_url = "hfs://resources"
    store_factory = partial(get_store_from_url, store_url)

    ParquetSerializer().store(
        store=store_factory(),
        key_prefix=file_name,
        df=df_expected,
    )
```

Parquet file generated is:
{"numbers":1,"codes":"R1"}
{"numbers":2,"codes":"G1"}
{"numbers":3,"codes":"B1"}

This is causing downstream applications to fail due to schema mismatch.

**Comment by lr4d** [comment]
@Waterfox83 the following code sample is practically doing the same as yours, and just checks that the restored dataframe is equal to the expected one, works fine for me
```
import pandas as pd
from functools import partial
from storefact import get_store_from_url
from kartothek.serialization import ParquetSerializer

from tempfile import TemporaryDirectory

df_expected = pd.DataFrame(
    {
        "numbers": [1, 2, 3],
        "colors": [None, None, None],
        "codes": ["R1", "G1", "B1"]
    }
)
file_name = "sampleDataset"
store_url = f"hfs://{TemporaryDirectory().name}"
store_factory = partial(get_store_from_url, store_url)

ParquetSerializer().store(
    store=store_factory(),
    key_prefix=file_name,
    df=df_expected,
)

df = ParquetSerializer.restore_dataframe(store=store_factory(), key=f"{file_name}.parquet")

import pandas.testing as pdt

pdt.assert_frame_equal(df, df_expected)
```

Are you reading the Parquet file with a different tool than kartothek?

**Comment by Waterfox83** [comment]
Yes. The parquet file being generated is being read by a Java application.

**Comment by lr4d** [comment]
@Waterfox83 I suspect this is caused by the tool you are using or perhaps some Python-Java Parquet incompatibility. What tool is it?

The column physically exists in the Parquet file:
```
from pyarrow.parquet import ParquetFile
path = f"{store_factory().root}/{list(store_factory().keys())[0]}"
p = ParquetFile(path)
p.schema
Out[13]:
<pyarrow._parquet.ParquetSchema object at 0x7fb220ce9ac8>
numbers: INT64
colors: INT32 UNKNOWN
codes: BYTE_ARRAY UTF8
```

**Comment by fjetter** [comment]
Indeed this sounds like an incompatibility between java reader and python/C++ writer

Can you provide an example of the java code you're using for reading?

**Comment by fjetter** [comment]
It might also be connected to something we do to the schema so we should verify that this is not on our side.

Can you try to use the following code to write the parquet file and see if this changes anything

```python
import pyarrow as pa
import pyarrow.parquet as pq
import pandas as pd
df = pd.DataFrame(
        {
            "numbers": [1, 2, 3],
            "colors": [None, None, None],
            "codes": ["R1", "G1", "B1"]
        }
    )
table = pa.Table.from_pandas(df)
pq.write_table(table, "filename")
```

```java
# read back in java
```

Also please provide the environment / versions you use. Especially pandas and pyarrow. We ask for this information in the issue template because we need to know how to reproduce any issues. You should also provide whatever java code you've been using to read this and the versions

**Comment by Waterfox83** [comment]
pandas: 0.24.2
pyarrow:0.15.1
Python 3.7.4

Using pq.write_table didn't have any change in final output. However, I found that in Java the schema has all columns but the data strips out the null column. Will give more details about Java code.
<img width="574" alt="Screenshot 2020-04-09 at 3 56 45 PM" src="https://user-images.githubusercontent.com/13029509/78886326-9eae2380-7a7b-11ea-9bea-770efa40818a.png">

**Comment by chaitanyalvk** [comment]
> Indeed this sounds like an incompatibility between java reader and python/C++ writer
> 
> Can you provide an example of the java code you're using for reading?

We are using the org.apache.parquet.hadoop Java library for reading the Parquets, using ParquetFileReader specifically.
This is the way we are reading from the Parquet.
String itemName = dataRow.getString(ITEM, 0); 
double oh = dataRow.getDouble(OH_SOURCE, 0);
//dataRow above is an instance of SimpleGroup.

Currently, for all blank columns, irrespective of the column datatype, we are receiving blank values("") in the parquet.
We are expecting default values based on the datatypes of the columns.
For example, the OH_SOURCE column above is a float column, so we are expecting a 0 as default.

**Comment by fjetter** [comment]
@Waterfox83 please provide a code example, the libraries with versions you were using and the representation of the output you got with that library. The above screenshot is some plugin for an IDE where we probably have no idea what's running in the background. This behaviour may be very different depending on what kind of library you are using and we want to find out if kartothek does anything which harms the compatibility or if it's just a misunderstood behaviour in the reader library.

**Comment by Waterfox83** [comment]
Sorry for late reply. Actually I was trying to check if there are any options/configs available with the library to suppress this behavior. We are using org.apache.parquet.parquet-avro library.

```
class Parquet {
  private List<SimpleGroup> data;
  private List<Type> schema;

  public Parquet(List<SimpleGroup> data, List<Type> schema) {
    this.data = data;
    this.schema = schema;
  }

  public List<SimpleGroup> getData() {
    return data;
  }

  public List<Type> getSchema() {
    return schema;
  }
}

 public static Parquet getParquetData(String filePath) throws IOException {
    List<SimpleGroup> simpleGroups = new ArrayList<>();
    ParquetFileReader reader = ParquetFileReader.open(HadoopInputFile.fromPath(new Path(filePath), new Configuration()));
    MessageType schema = reader.getFooter().getFileMetaData().getSchema();
    List<Type> fields = schema.getFields();
    PageReadStore pages;
    while ((pages = reader.readNextRowGroup()) != null) {
      long rows = pages.getRowCount();
      MessageColumnIO columnIO = new ColumnIOFactory().getColumnIO(schema);
      RecordReader recordReader = columnIO.getRecordReader(pages, new GroupRecordConverter(schema));

      for (int i = 0; i < rows; i++) {
        SimpleGroup simpleGroup = (SimpleGroup) recordReader.read();
        simpleGroups.add(simpleGroup);
      }
    }
    reader.close();
    return new Parquet(simpleGroups, fields);
  }
}
```

**Comment by chaitanyalvk** [comment]
> Indeed this sounds like an incompatibility between java reader and python/C++ writer
> 
> Can you provide an example of the java code you're using for reading?

We are using org.apache.parquet.hadoop Java libraries for reading the Parquets, using ParquetFileReader specifically.
long ohPost = dataRow.getLong(OHPOST_SOURCE, 0);
String dest = dataRow.getString(DEST, 0);
//dataRow above is an instance of SimpleGroup.

**Comment by Waterfox83** [comment]
I am also trying to find out if this is a known issue with the library? https://stackoverflow.com/questions/61120411/using-parquet-avro-library-in-java-to-read-parquet-file-written-using-pyarrow

**Comment by Waterfox83** [comment]
I am closing this issue till there is something concrete to prove that there is any issue with ParquetSerializer. At present it seems like something to do with the parquet-avro. Thanks for looking into it.
