### ISSUE TITLE
read data by partition

### ISSUE THREAD

**Issue by brl0** [JDASoftwareGroup/kartothek#285]
I would like to iterate over and read the partitions in a dataset.  

Using `DatasetFactory.dataset_metadata.partitions` I can get the `files` attribute for the individual partitions, and could then read the parquet file directly.  

Is there is a better way to do this?

I'm trying to do something roughly like:
```
for partition in dataset1:
    ddf = read(partition)
    results = process(ddf)
    update_dataset_from_ddf(results, dataset_uuid="dataset2", ...)
```

Let me know if I need to clarify my question, or if there is a better place to ask.
Thanks in advance for your assistance.

**Comment by fjetter** [comment]
We offer this in the `io.iter` submodule

```
from kartothek.io.iter import read_dataset_as_dataframes__iter

ds_iterator = read_dataset_as_dataframes__iter(
    ...
)
for partition in ds_iterator:
    assert isinstance(partition, pd.DataFrame)
```

see https://kartothek.readthedocs.io/en/latest/api.html#iter

what you do with the idividual partitions is up to you, of course. your example would commit every partition individually to some other dataset. If you want to stay within a generator context and only want to commit once the entire generator is consumed, you can do

```
ds_iterator = read_dataset_as_dataframes__iter(
    ...
)
intermediate_gen_expression = (
    apply_function(chunk) for chunk in ds_iterator
)
update_dataset_from_dataframes__iter(
    intermediate_gen_expression,
    ...
)
```

(This interface does not use dask)

**Comment by brl0** [comment]
Thanks for your help.  This is exactly what I was looking for.
