### ISSUE TITLE
read_dataset_as_ddf and update_dataset_from_ddf raise if optional table argument is not provided.

### ISSUE THREAD

**Issue by mlondschien** [JDASoftwareGroup/kartothek#288]
### Problem description

The `read_dataset_as_ddf` function has an optional argument `table`. However if not provided, a `KeyError` will raise [here](https://github.com/JDASoftwareGroup/kartothek/blob/f7dc8f985414801b115842a169805344cf1378a5/kartothek/io/dask/dataframe.py#L104). Similarly, the `table` argument of the `update_dataset_from_ddf` function is optional according to the docs, but will result in a `TypeError` [here](https://github.com/JDASoftwareGroup/kartothek/blob/f7dc8f985414801b115842a169805344cf1378a5/kartothek/io/dask/dataframe.py#L230).

### Possible solutions

A simple solution would be to pass `"table"` (or rather `kartothek.io_components.metapartition.SINGLE_TABLE`) as a default value. This however would raise the question why the function is called `read_dataset_as_ddf` rather than `read_table_as_ddf`, especially as `read_table_as_delayed` is called within `read_dataset_as_ddf`, so maybe there exists a less obvious solution.

**Comment by lr4d** [comment]
I think having `kartothek.io_components.metapartition.SINGLE_TABLE` as the default argument for `table` makes sense, as we do now for `read_table` if I remember correctly.
Do you have time to open a PR for this?

FYI for the next major release, we intend to drop the multi-table functionality entirely
