### ISSUE TITLE
update_dataset_from_ddf should return scalar instead of delayed object

### ISSUE THREAD

**Issue by fjetter** [JDASoftwareGroup/kartothek#301]
### Problem description

The function `update_dataset_from_ddf` currently returns a delayed object instead of a DataFrame-like object. This has impact on how dask treats the computation, in particular what optimizations are applied. delayed objects have no default optimiser registered which may heavily and negatively impact the performance.

We should be able to avoid this issue by using the dask.DataFrame API, e.g.

```
# This would return a dask scalar instead of a dask.delayed
ddf.reduction(
    perpartition=..., # build indices, etc.
    aggregate=update_dataset_from_partitions,
    split_every=False,
    name="commit-dataset",
)
```
https://github.com/JDASoftwareGroup/kartothek/blob/0371eed190100463e7a46bfa630fd13ce2d2965f/kartothek/io/dask/dataframe.py#L295

The issue here is that one might argue that the return type is part of the signature and therefore this would be a breaking change. Benefits might be huge, though.

**Comment by lr4d** [comment]
What if we just return the delayed object optimized with `dask.dataframe.optimize`?

**Comment by fjetter** [comment]
I thought about building in an optimization step myself. I think that would be a viable approach. otoh, I wouldn't mind a breaking release soon

**Comment by lr4d** [comment]
Unless somebody is doing some hacky stuff with the returned graph (which they "shouldn't" be doing), I think it's quite safe and very reasonable to have that optimization step
