### ISSUE TITLE
Refactor `Metapartition`

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#312]
Example problem
- A user cannot be certain of calling e.g. `to_dict` on a metapartition and receiving a return value, because a `Metapartition` can be a wide range of things

Intention: Make sure that the fundamental methods of `Metapartition` can be called in a straightforward manner

Suggestions
- Have separate data types for "`Metapartition` with data loaded", "`Metapartitions` having a _reference_ to data" and "empty`Metapartitions` (no data or metadata attached)"
- At the moment since a single metapartition can be a "collection of Metapartitions", some operations require iterating over the metapartition to make a method call succesful

**Comment by fjetter** [comment]
I would rather suggest to make MP private / non user facing. Refactoring is still required but not to improve usability for end-users

**Comment by fjetter** [comment]
I will close this issue since the MP is not supposed to be user facing any more with ktk 4.0
I believe there are many chances to refactor it but we'd need a more concrete use case than merely refactoring
