### ISSUE TITLE
Deprecate read support for multi tabled datasets

### ISSUE THREAD

**Issue by fjetter** [JDASoftwareGroup/kartothek#317]
In our efforts to deprecated the in-dataset multi table functionality, the first step will be to deprecate and remove the possibility to read from a multi tabled dataset. The first step should be to detect multi tabled datasets during reading and issue a deprecation warning.

The second phase will then be to only allow reading from a single valued dataset, rendering the `table` kwarg obsolete, defaulting to whatever table exists in the dataset. In phase two we may also remove support in the write operation, s.t. it always defaults to SINGLE_TABLE unless in update mode.

Third phase (hard breaking) would be to drop the support entirely and replace the current metadata specification with a new version.

**Comment by lr4d** [comment]
Do you envision a time line for each phase?

**Comment by lr4d** [comment]
First phase checklist:
- [ ] issue warning when reading multiple tables (done in #337)
- [ ] at least the dict type kwargs for categoricals and columns also need to be adapted (potentially more, check this)
- [ ] there are also the functions which only work on a single table (e.g. everything in dask.dataframe and something like eager.read_table) which should issue a warning if the requested table is not the SINGLE_TABLE constant

**Comment by imkumarg** [comment]
Okay in PR #349, I will address the first, third and fourth point.
