### ISSUE TITLE
Simple utility function to get pyarrow schema from dataset

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#343]
Something like:
```python
from kartothek.core.dataset import DatasetMetadata
from kartothek.core.factory import DatasetFactory
from kartothek.io_components.metapartition import SINGLE_TABLE


def get_pyarrow_schema(factory: DatasetFactory, table: str = SINGLE_TABLE):
    dm = DatasetMetadata(uuid=factory.dataset_uuid).load_from_store(
        uuid=factory.dataset_uuid, store=factory.store_factory()
    )
    schema_wrapper = dm.table_meta[table]
    schema = schema_wrapper.internal()
    return schema
```

**Comment by fjetter** [comment]
The factory forwards all methods and attribute access to the underlying metadata. Therefore the following should be sufficient.

```python
factory.table_meta["table"].internal()
```

That doesn't really justify a dedicated function, does it?

**Comment by lr4d** [comment]
Thanks @fjetter . I think UX-wise we could still improve a bit, as I'm not sure how clear it is that `table_meta[table].internal()` returns a pyarrow table

**Comment by lr4d** [comment]
e.g. we could expose a `pyarrow_schema` property to `DatasetFactory`

**Comment by fjetter** [comment]
There is now `DatasetMetadata.schema` / `DatasetFactory.schema`
