### ISSUE TITLE
Optimize dask graphs properly

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#354]
### Problem description

Our dask update graphs are not properly optimized.

We ussually use dask.dataframe optimization and set `ave_width=repartition_ratio` for `kartothek.io.dask.dataframe.update_dataset_from_ddf` graphs. We should return an optimized graph from update_dataset_from_ddf to make our users' life simple.

We already have code that does this, whoever picks this up can ping me or @fjetter to be pointed to that.

**Comment by fjetter** [comment]
Note that implementing #301 would offer a similar functionality.

**Comment by lr4d** [comment]
Except for the `ave_width=repartition_ratio` parameter, possibly other optimization parameters used for bag?
