### ISSUE TITLE
Argument dispatch_by=[] is ignored when reading dataset

### ISSUE THREAD

**Issue by mlondschien** [JDASoftwareGroup/kartothek#368]
### Problem description

Currently passing `dispatch_by = []` to `read_...` behaves as passing `dispatch_by = None`.

### Example code (ideally copy-pastable)

```python
In [2]: import pandas as pd
   ...: import storefact
   ...: from functools import partial
   ...: from kartothek.io.eager import store_dataframes_as_dataset
   ...: from kartothek.io.dask.dataframe import read_dataset_as_ddf
   ...: 
   ...: path = "/tmp"
   ...: uuid = "dataset"
   ...: df = pd.DataFrame({"x": [1, 2], "y": ["a", "b"]})
   ...: store = partial(storefact.get_store_from_url, f"hfs://{path}?create_if_missing=False")
   ...: dm = store_dataframes_as_dataset(
   ...:     dfs=[df],
   ...:     dataset_uuid=uuid,
   ...:     store=store,
   ...:     partition_on=["x"],
   ...:     overwrite=True,
   ...: )
   ...: 
   ...: ddf = read_dataset_as_ddf(dataset_uuid=uuid, store=store, dispatch_by=[])
   ...: ddf.npartitions
   ...: 
Out[2]: 2

```

### Used versions

This was run on master.

**Comment by fjetter** [comment]
I assume you'd want `dispatch_by=[]` to merge all dataset partitions into a single dask partition, correct?

**Comment by mlondschien** [comment]
Sorry for prematurely opening a PR. I might have underestimated the complexity here :D. I marked it as draft.

> I assume you'd want dispatch_by=[] to merge all dataset partitions into a single dask partition, correct?

Yes. I thought that the natural behaviour would be to have `dispatch_by=[]` return one single partition and `dispatch_by=None` return one partition for every parquet file. However in `normalize_args` you are (actively) replacing `dispatch_by=None` with `dispatch_by=[]`. Do you have any use-case for this? Is there a specific reason to maintain the current behaviour?

**Comment by fjetter** [comment]
Sorry for taking so long to reply. I think this makes sense. It's worth mentioning that we have a "competing" interface in the cubes with the parameter `partition_by` where the default behaviour is actually to just return a single partition. I believe we're missing the option to "not apply any further logic" there which is why I do like this proposal. Ultimately, I would like the two to behave identical.

@marco-neumann-by you have a deeper insight into how and why this is the case for the cubes.

The proposal

None: apply no logic
[]: Compress everything into one partition
["fieldA", ...]: dispatch/partition by what is provided

sounds reasonable to me but I'd like another opinion for this

**Comment by marco-neumann-by** [comment]
The "apply no logic" doesn't make sense for cubes (at least with the current implementation), because the alignment of multiple datasets works based on logical partitions, so just streaming out parquet files doesn't work there.

**Comment by mlondschien** [comment]
Thanks for the response. Note that this is not about the behaviour for `dispatch_by=None` but rather `dispatch_by=[]`. I assume `dispatch_by=[]` returns one single partition for cubes (as `dispatch_by=None`)?

**Comment by marco-neumann-by** [comment]
> I assume `dispatch_by=[]` returns one single partition for cubes (as `dispatch_by=None`)?

W/o looking at the code I think that should be the behavior.

**Comment by fjetter** [comment]
> The "apply no logic" doesn't make sense for cubes

That's what I thought. I just noticed that the default behaviour for cubes is at the moment to partition_by/dispatch_by to a single dataframe. I guess this is a question about sane defaults.

I believe the cases `[]` and `["field", ...]` are pretty clear and should work as described here. The behaviour for `None` should then probably be "sane default for the given implementation". 
Sane default imo
plain dataset -> one job per file
cube -> one job per logical partition / partition key tuple

does that make sense?

**Comment by marco-neumann-by** [comment]
Sounds good 👍
