### ISSUE TITLE
remove_partitions function for data cube doesn't work

### ISSUE THREAD

**Issue by jw-cpnet** [JDASoftwareGroup/kartothek#379]
### Problem description

remove_partitions cannot remove any partition. The data is partitioned using "year", "month" and "day". It is stored in Azure Blob Storage:

![image](https://user-images.githubusercontent.com/44900488/101019111-70033100-35a7-11eb-8b8f-b5c4a0d4f998.png)

I can query with the same condition but cannot remove the partition

### Example code (ideally copy-pastable)

Please provide a minimal reproducible code example to reproduce the behavior,
c.f. https://stackoverflow.com/help/minimal-reproducible-example

```python
import pandas as pd
from functools import partial
from kartothek.core.cube.conditions import C
from kartothek.core.cube.cube import Cube
from kartothek.io.eager_cube import (
    append_to_cube,
    build_cube,
    query_cube,
    remove_partitions,
)
from storefact import get_store_from_url

def _define_cube():
    account_name = AZURE_STORAGE_ACCOUNT
    account_sas = AZURE_STORAGE_SAS_TOKEN
    pdline = PRODUCTION_LINE
    cube_container = f"data-cube-{pdline}".lower()
    store_url = (
        f"hazure://{account_name}:{account_sas}@{cube_container}"
        "?use_sas=true&create_if_missing=false"
    )
    store_factory = partial(get_store_from_url, store_url)
    store = store_factory()
    cube = Cube(
        uuid_prefix="contextualizeddata",
        dimension_columns=["minute_level"],
        partition_columns=["year", "month", "day"],
    )

    return store, cube

store, cube = _define_cube()

remove_partitions(cube=cube, store=store, ktk_cube_dataset_ids=['seed'], conditions=((C('year')==2020) & (C('month')==12) & (C('day')==2)))
```

### Used versions

<details>

```
$ pip freeze | grep -i kartothek
kartothek==3.17.2
```

</details>

**Comment by jw-cpnet** [comment]
Sorry for the false alarm. The SAS token I was using didn't contain DELETE permission. That's the reason why the blob was not deleted. There was no error raised. Thank you for your attension!

**Comment by jw-cpnet** [comment]
I have to use `garbage_collect_dataset` after calling `remove_partitions` or the physical partition won't be removed. `remove_partitions` alone is not enough. Is this behavior intentional?

**Comment by fjetter** [comment]
> I have to use garbage_collect_dataset after calling remove_partitions or the physical partition won't be removed. remove_partitions alone is not enough. Is this behaviour intentional?

Yes this is intended behaviour. This way we can perform the delete in one atomic operation and for kartothek it doesn't really matter whether or not the files are actually there. We just no longer reference it.

The garbage collect is important if you intend to consume the dataset using other readers which only accept a hive like partitioning. otherwise you could safely ignore this GC

**Comment by jw-cpnet** [comment]
Thank you for the clarification! 

> The garbage collect is important if you intend to consume the dataset using other readers which only accept a hive like partitioning. otherwise you could safely ignore this GC

This is interesting. Would it be better to mention this in the Kartothek Cube doc, e.g. as a hint for `remove_partitions`?
