### ISSUE TITLE
Use caching of Python environments to speed up CI

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#394]
### Problem description

Our CI takes some time to run, a significant chunk of this time is spent on creating the required Python environment.

We can speed this up by using caching every new created environment, so that we don't need to create the same environment more than once. (We may have to remove old environments eventually)

We can use https://github.com/actions/cache for this

**Comment by fjetter** [comment]
I'm against this since I believe our primary problem of CI is that the test matrix is too large, not that individual jobs are running too long (that as well but that's linked to blown up parameterizations and slow tests). 

Caching introduces all kinds of nasty to debug issues linked to cache invalidation or stale caches

**Comment by lr4d** [comment]
>  I believe our primary problem of CI is that the test matrix is too large,

That's probably true, although it may be less trivial to solve
Looking at CI times, creating the environment (including conda bootstapping) takes up to 2min 50s. Running tests takes around 10min, 30s. (ref: https://github.com/JDASoftwareGroup/kartothek/runs/1727072228?check_suite_focus=true)

> Caching introduces all kinds of nasty to debug issues linked to cache invalidation or stale caches

Have you run into this using `actions/cache`? From my limited experience with it, it has worked quite well

**Comment by fjetter** [comment]
> Have you run into this using actions/cache?

Haven't tried actions/cache yet. Question would be how this caching actually works, e.g. when is the cache invalidated?
It must be invalidated at some point, otherwise we'd run with the same set of requirements until the end of time

**Comment by lr4d** [comment]
What you do (again, given my limited experience) is you provide a string to identify the cache, which will usually be composed of composed of something like `(python version)-hash(requirements)-hash(test-requirements)`.
Then, on the next run you check if that string is already present in the cache, if it is, then you restore the cache, otherwise you create another entry

**Comment by fjetter** [comment]
`hash(requirements including version)` will always be the same unless we change a pinning. therefore, the cache will in practice only very rarely be invalidated
