### ISSUE TITLE
Isolate CI workflows/jobs into lint/test/release

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#395]
### Problem description
If CI fails at the moment, it could be because linting has gone wrong, test have failed or the release has failed.

IMO, it makes more sense to have a separate workflow/job for linting, and for release, isolated from testing. This way, it is easier for a contributor to spot what part of the job has failed.

Isolating linting from testing would also speed up the CI as we would no longer need to lint for every combination of the CI matrix.

Separating the workflows/jobs into its separate components would also simplify the CI code, which is becoming quite spaghetti-like

**Comment by fjetter** [comment]
I would suggest to use pre-commit for the linting part. this way everything is ensured to be aligned. E.g. https://github.com/dask/distributed/blob/master/.github/workflows/ci-pre-commit.yml
