### ISSUE TITLE
Compatibility with numpy 1.20.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [JDASoftwareGroup/kartothek#396]
Just as a heads up, apart from a bunch of deprecation warnings when running the tests, there are also a few failures in the kartothek test suite when using the newly release numpy 1.20.0.

This is caused by https://github.com/numpy/numpy/issues/18287, which is already fixed and will probably be in an upcoming 1.20.1 release (but can also be fixed by changing `np.unicode` to `str`)

Example failure:

```
 ____________ ERROR collecting tests/io/dask/dataframe/test_read.py _____________
tests/io/dask/dataframe/test_read.py:185: in <module>
    @pytest.mark.parametrize("col", get_dataframe_not_nested().columns)
kartothek/core/testing.py:65: in get_dataframe_not_nested
    "unicode": pd.Series(["Ö"], dtype=np.unicode),
/opt/conda/envs/arrow/lib/python3.7/site-packages/pandas/core/series.py:335: in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
/opt/conda/envs/arrow/lib/python3.7/site-packages/pandas/core/construction.py:480: in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
/opt/conda/envs/arrow/lib/python3.7/site-packages/pandas/core/construction.py:587: in _try_cast
    maybe_cast_to_integer_array(arr, dtype)
/opt/conda/envs/arrow/lib/python3.7/site-packages/pandas/core/dtypes/cast.py:1723: in maybe_cast_to_integer_array
    casted = np.array(arr, dtype=dtype, copy=copy)
E   ValueError: invalid literal for int() with base 10: 'Ö'
```

Noticed this in the pyarrow nightly integration builds, see https://issues.apache.org/jira/browse/ARROW-11472. And since I did the effort to figure out the cause, I thought to spare you the time ;)

**Comment by fjetter** [comment]
That's incredibly helpful. I believe we're good with the `str` type. We had it very explicit due to py2/3 compat but these days are thankfully gone :D

I'll prepare a PR
