### ISSUE TITLE
releases do not update "stable" documentation

### ISSUE THREAD

**Issue by steffen-schroeder-by** [JDASoftwareGroup/kartothek#412]
### Problem description
Sometimes since after 3.18.0, creating a new release does not update the https://kartothek.readthedocs.io/en/stable/changes.html page. It still points to 3.18.0, but should point to 3.19.0.
https://kartothek.readthedocs.io/en/latest/changes.html contains 3.19.0

Possibly related PR: https://github.com/JDASoftwareGroup/kartothek/pull/392

**Comment by fjetter** [comment]
should be fixed. was a misconfig of readthedocs. not related to the PR

**Comment by fjetter** [comment]
FYI: build is running, should be there in 5-10min
