### ISSUE TITLE
Add documentation about store factories

### ISSUE THREAD

**Issue by fjetter** [JDASoftwareGroup/kartothek#44]
We heavily rely on the usage of store factories to not (attempt to) serialize connections. We should add a section to the documentation explaining the reasoning, introduce examples and establish best practices (e.g. don't use lambdas)

**Comment by lr4d** [comment]
A basic documentation about stores exists now in https://github.com/JDASoftwareGroup/kartothek/pull/62. This tells the user to use store factories and recommends storefact `h`-stores. It could of course always be expanded
