### ISSUE TITLE
Index build pipeline for dask backends

### ISSUE THREAD

**Issue by fjetter** [JDASoftwareGroup/kartothek#45]
The implementation for a build_indices pipeline is currently missing for the dask.delayed and dask.dataframe. An implementation should be available with the functionality of https://github.com/JDASoftwareGroup/kartothek/blob/36cb7f7ecbab692f68d8c0bf80463447dad6346c/kartothek/io/eager.py#L694

**Comment by lr4d** [comment]
Isn't this resolved by https://github.com/JDASoftwareGroup/kartothek/pull/75 ?
