### ISSUE TITLE
Normalize input to `list` properly in `normalize_args`

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#56]
Currently, if a user wants to partition along column "x", and since columns are unique, thinks it is appropriate to provide a set as the value to the argument e.g. `partition_on={"x"}`; this would be "normalized" to `[{"x"}]` ( a list of sets), and then an error will be raised at some other part of the code where this input is unexpected.
The expected behavior of the normalization would be to normalize sets, tuples or similar iterables to a list such as `["x"]` (a list of strings).

I do not consider this a bug as in the docs it states `partition_on` should be provided as a list.

Normalization function: `kartothek.io_components.utils.normalize_arg`

**Comment by fjetter** [comment]
Sets can not be properly normalized since they don't preserve order. For 'partition_on' the order is quite important, i.e. a set would be an incompatible input

**Comment by crepererum** [comment]
Same goes for dicts, which are iterable but don't have a nice, semantic order.

**Comment by lr4d** [comment]
@fjetter Right, you told me this once already but I forgot.
Anyways, this issue would still make some sense regarding tuples. And if types such as sets or dicts should be disallowed, why not also do so properly during argument parsing instead of waiting for an exception to be raised at a later point of the execution?

**Comment by crepererum** [comment]
I'm always in favor of parsing / checking arguments early, especially BEFORE the computation is submitted to dask/distributed or to an iterator, because UX ftw!

**Comment by lr4d** [comment]
Hint: the following could be a start to parse `(0,1)` to `[0,1]` instead of the current `[(0,1)]`.
```
def _make_list(x):
    if isinstance(x, (str, bytes)):
        return [x]
    return list(x)
```
```
    elif old_value is None:
        new_value = _ARGS_TO_TYPE[arg_name]()
```
