### ISSUE TITLE
Test compatiblity with Hive and Spark

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#68]
According to our open-sourcing blog post, kartothek "is designed with compatibility in mind to the implicit standard storage layout used by Dask, Spark, Hive and more."

If we advertise this, shouldn't we test that Spark and Hive are able to read the Parquet files produced by kartothek?

@crepererum commented to me that he was unable to read the files in a language other than Python, because of some timestamp issue if I remember correctly.

**Comment by crepererum** [comment]
> @crepererum commented to me that he was unable to read the files in a language other than Python, because of some timestamp issue if I remember correctly.

Exactly. The parquet files I have in production us timestamps with `ns` resolution which seems to be a problem for many other parquet readers. We should probably use the entire set of types we already have in [`get_dataframe_not_nested`](https://github.com/JDASoftwareGroup/kartothek/blob/cf66b7527ec5f045c482d56ebf7cfe2514ffc3bc/kartothek/core/testing.py#L47) for non-index columns, primary index columns and secondary index columns.

**Comment by xhochy** [comment]
Timestamp support in Parquet land is a mess. `TIMESTAMP_MILLIS` is currently the best supported one, it can be read by all latest releases of the artifacts. Spark and Hive still prefer the INT96 timestamp with nanosecond precision while there is a `TIMESTAMP_NANOS` in Parquet that is supported by parquet-cpp and parquet-rust releases but yet only in parquet-mr's master.

**Comment by lr4d** [comment]
Basic hive compatibility fixed with https://github.com/JDASoftwareGroup/kartothek_hive_integration_test

**Comment by xhochy** [comment]
@lr4d This is a private repo. Do you plan to opensource this as well?

**Comment by gabriel-kohen-jdas** [comment]
@xhochy , the test repository is now public.

**Comment by xhochy** [comment]
Thanks!
