### ISSUE TITLE
Kartothek breaks with pyarrow 0.14.0

### ISSUE THREAD

**Issue by fjetter** [JDASoftwareGroup/kartothek#81]
Not surprised but a bit disappointed, we have breakage with the new arrow release, e.g. https://travis-ci.org/fjetter/kartothek/builds/554210679

**Comment by fjetter** [comment]
There are even segfaults 🎉

**Comment by fjetter** [comment]
https://issues.apache.org/jira/browse/ARROW-5873

**Comment by fjetter** [comment]
https://issues.apache.org/jira/browse/ARROW-5878

**Comment by fjetter** [comment]
Ihttps://issues.apache.org/jira/browse/ARROW-5889

**Comment by fjetter** [comment]
I suggest to postpone arrow 0.14.x support until 0.14.1 / https://issues.apache.org/jira/browse/ARROW-5878 is resolved. This seemed to have triggered a discussion regarding the parquet spec and I think we should sit this one out

**Comment by crepererum** [comment]
Fair, let's blacklist 0.14.0 then in our requirements.

**Comment by byjott** [comment]
So 0.14.1 has been released. What's the status with that version?

**Comment by fjetter** [comment]
There is a WIP https://github.com/JDASoftwareGroup/kartothek/pull/108

**Comment by xhochy** [comment]
We support 0.14.1 and explicitly omit 0.14, closing this as won't fix.
